### ISSUE TITLE
s-bind leads to twice escaped ampersand

### ISSUE THREAD

**Issue by tarantuli** [sfire-framework/sfire-template#1]
Template source:
`                <td><a s-bind:href="'?p=PlanCare_localstore_updates&updateID='. $item['updateID']">{{ $item['name']
                        }}</a></td>
`

Rendered HTML (slightly sanitized):
`<td><a href="?p=PlanCare_localstore_updates&amp;amp;updateID=ID">NAME</a></td>`

Versions:
sfire-framework/sfire-datacontrol  1.0.2    Library for hashing data, generation of tokens and converting/formatting strings, numbers and arrays.
sfire-framework/sfire-dom          1.0.4    HTML / XML parser
sfire-framework/sfire-filecontrol  1.0.3    Working with files, directories and mime types
sfire-framework/sfire-localization 1.0.1    Provides a convenient way to retrieve strings in various languages, allowing you to easily support multiple languages within your application
sfire-framework/sfire-store        1.0.1    Singleton containers for storing and retrieving arbitrary data keeping the state until the end of the run.
sfire-framework/sfire-template     1.0.5    Template parser based on Vuejs

**Comment by sfire-framework** [comment]
Thank you for the report. This issue is already been patched. Therefore this ticket will be closed.
